[project]
name = "module-chat"
version = "0.1.0"
description = ""
authors = [
    {name = "Thais Carolina Braga de MagalhÃ£es",email = "tcbdma.snf24@uea.edu.br"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
]

[tool.poetry]
packages = [{include = "module_chat", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
